# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: technical-interview-report

on:
  push:
    branches:
      - v2
      - develop
      - main
  pull_request:
    branches:
      - v2
      - develop
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2 and pypy3
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=30 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
